# Generated by Django 5.1.3 on 2024-11-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("make", models.CharField(max_length=30)),
                ("model", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("car_length", models.FloatField()),
                ("electrified", models.BooleanField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
