# Generated by Django 5.1.3 on 2024-11-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park_smart_analytics", "0002_lots_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="lots",
            name="handicap",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lots",
            name="handicap_available",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lots",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
