# Generated by Django 5.1.3 on 2024-11-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "park_smart_analytics",
            "0003_lots_handicap_lots_handicap_available_alter_lots_id",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lots",
            name="lot_id",
            field=models.CharField(
                default=0, editable=False, max_length=20, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lots",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
