# Generated by Django 5.1.3 on 2024-11-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park_smart_analytics", "0004_lots_lot_id_alter_lots_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lots",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
