# Generated by Django 5.1.3 on 2024-11-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park_smart_analytics", "0005_alter_lots_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="checked_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="checked_in_disability",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="checked_in_electric",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
