# Generated by Django 5.1.3 on 2024-11-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("park_smart_analytics", "0006_buildings_buildinglotdistance_lotlotdistance"),
        (
            "park_smart_analytics",
            "0006_user_checked_in_user_checked_in_disability_and_more",
        ),
    ]

    operations = []
