from django.core.management.base import BaseCommand

from park_smart_analytics.models import Lots


class Command(BaseCommand):
    help = "Add initial data to the Lots table"

    def handle(self, *args, **kwargs):
        # Check if data already exists to prevent duplicate entries
        if Lots.objects.exists():
            self.stdout.write(
                self.style.WARNING("Data already exists. Exiting script.")
            )
            return

        # Add data to the database
        lots_data = [
            {
                "name": "North Lot",
                "total": 200,
                "available": 200,
                "electrified": 10,
                "electrified_available": 0,
                "handicap": 5,
                "handicap_available": 5,
            },
            {
                "name": "Academy Hall Lot",
                "total": 100,
                "available": 100,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 2,
                "handicap_available": 2,
            },
            {
                "name": "Mueller Center Public Lot",
                "total": 50,
                "available": 35,
                "electrified": 10,
                "electrified_available": 0,
                "handicap": 6,
                "handicap_available": 6,
            },
            {
                "name": "Mueller Center Gated Lot",
                "total": 30,
                "available": 30,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 0,
                "handicap_available": 0,
            },
            {
                "name": "Union Short Term Lot",
                "total": 6,
                "available": 6,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 1,
                "handicap_available": 1,
            },
            {
                "name": "Union Lot",
                "total": 15,
                "available": 15,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 0,
                "handicap_available": 0,
            },
            {
                "name": "AS&RC Lot",
                "total": 20,
                "available": 20,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 0,
                "handicap_available": 0,
            },
            {
                "name": "Commons Lot",
                "total": 40,
                "available": 40,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 2,
                "handicap_available": 2,
            },
            {
                "name": "Parking Structure",
                "total": 200,
                "available": 200,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 5,
                "handicap_available": 5,
            },
            {
                "name": "Front Academy Lot",
                "total": 15,
                "available": 15,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 0,
                "handicap_available": 0,
            },
            {
                "name": "Admissions Lot",
                "total": 15,
                "available": 15,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 2,
                "handicap_available": 2,
            },
            {
                "name": "Alumni House Lot",
                "total": 20,
                "available": 20,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 0,
                "handicap_available": 0,
            },
            {
                "name": "H Building Lot",
                "total": 10,
                "available": 10,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 1,
                "handicap_available": 1,
            },
            {
                "name": "J Building Lot",
                "total": 30,
                "available": 30,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 0,
                "handicap_available": 0,
            },
            {
                "name": "Clubhouse Lot",
                "total": 3,
                "available": 3,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 3,
                "handicap_available": 3,
            },
            {
                "name": "Blitman Lot",
                "total": 100,
                "available": 100,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 2,
                "handicap_available": 2,
            },
            {
                "name": "RAHPs A Lot",
                "total": 50,
                "available": 50,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 0,
                "handicap_available": 0,
            },
            {
                "name": "RAHPs B Lot",
                "total": 50,
                "available": 50,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 0,
                "handicap_available": 0,
            },
            {
                "name": "Stackwyck Lot",
                "total": 50,
                "available": 50,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 0,
                "handicap_available": 0,
            },
            {
                "name": "Brickwyck Lot",
                "total": 50,
                "available": 50,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 0,
                "handicap_available": 0,
            },
            {
                "name": "West Hall Lot",
                "total": 60,
                "available": 60,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 2,
                "handicap_available": 2,
            },
            {
                "name": "Winslow Lot",
                "total": 30,
                "available": 30,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 2,
                "handicap_available": 2,
            },
            {
                "name": "Nason Hall Lot",
                "total": 50,
                "available": 50,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 4,
                "handicap_available": 4,
            },
            {
                "name": "Bray Hall Lot",
                "total": 30,
                "available": 30,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 0,
                "handicap_available": 0,
            },
            {
                "name": "Nugent Lot",
                "total": 30,
                "available": 30,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 0,
                "handicap_available": 0,
            },
            {
                "name": "Sharp Lot",
                "total": 40,
                "available": 40,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 0,
                "handicap_available": 0,
            },
            {
                "name": "BARH Lot",
                "total": 110,
                "available": 110,
                "electrified": 4,
                "electrified_available": 4,
                "handicap": 3,
                "handicap_available": 3,
            },
            {
                "name": "Field House Lot",
                "total": 45,
                "available": 45,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 0,
                "handicap_available": 0,
            },
            {
                "name": "Lower ECAV Lot",
                "total": 60,
                "available": 60,
                "electrified": 10,
                "electrified_available": 0,
                "handicap": 5,
                "handicap_available": 5,
            },
            {
                "name": "Upper ECAV Lot",
                "total": 50,
                "available": 50,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 0,
                "handicap_available": 0,
            },
            {
                "name": "Renwyck Lot",
                "total": 10,
                "available": 10,
                "electrified": 0,
                "electrified_available": 0,
                "handicap": 2,
                "handicap_available": 2,
            },
        ]

        for lot_data in lots_data:
            lot, created = Lots.objects.get_or_create(**lot_data)
            if created:
                self.stdout.write(self.style.SUCCESS(f"Added {lot}"))

        self.stdout.write(self.style.SUCCESS("Initial data added successfully"))
